"""add_banned_lists

Revision ID: 4a02c4ce276e
Revises: 2c9d6fa97e0c
Create Date: 2026-05-25 08:32:11.016041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a02c4ce276e'
down_revision: Union[str, None] = '2c9d6fa97e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_domains',
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('banned_keywords',
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('keyword')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned_keywords')
    op.drop_table('banned_domains')
    # ### end Alembic commands ###